const djsdocs = [
  {
    name: "Discord.js/stable",
    url: "https://raw.githubusercontent.com/discordjs/docs/main/discord.js/stable.json",
    github: "https://github.com/discordjs/discord.js/tree/stable/",
    branch: "stable",
    doc: "https://discord.js.org/#/docs/discord.js/stable/",
    data: "",
    search: [],
    classes: [],
    typedefs: [],
  },
  {
    name: "Discord.js/main",
    url: "https://raw.githubusercontent.com/discordjs/docs/main/discord.js/main.json",
    github: "https://github.com/discordjs/discord.js/tree/main/",
    branch: "main",
    doc: "https://discord.js.org/#/docs/discord.js/main/",
    data: "",
    search: [],
    classes: [],
    typedefs: [],
  },
  {
    name: "Collection/stable",
    url: "https://raw.githubusercontent.com/discordjs/docs/main/collection/stable.json",
    github: "https://github.com/discordjs/collection/tree/stable/",
    branch: "stable",
    doc: "https://discord.js.org/#/docs/collection/stable/",
    data: "",
    search: [],
    classes: [],
    typedefs: [],
  },
  {
    name: "Collection/main",
    url: "https://raw.githubusercontent.com/discordjs/docs/main/collection/main.json",
    github: "https://github.com/discordjs/discord.js/tree/main/",
    branch: "main",
    doc: "https://discord.js.org/#/docs/collection/main/",
    data: "",
    search: [],
    classes: [],
    typedefs: [],
  },
  {
    name: "Builders/stable",
    url: "https://raw.githubusercontent.com/discordjs/docs/main/builders/stable.json",
    github: "https://github.com/discordjs/builders/tree/stable/src/",
    branch: "stable",
    doc: "https://discord.js.org/#/docs/builders/stable/",
    data: "",
    search: [],
    classes: [],
    typedefs: [],
  },
  {
    name: "Builders/main",
    url: "https://raw.githubusercontent.com/discordjs/docs/main/builders/main.json",
    github: "https://github.com/discordjs/discord.js/tree/main/",
    branch: "main",
    doc: "https://discord.js.org/#/docs/builders/main/",
    data: "",
    search: [],
    classes: [],
    typedefs: [],
  },
  {
    name: "Voice/stable",
    url: "https://raw.githubusercontent.com/discordjs/docs/main/voice/stable.json",
    github: "https://github.com/discordjs/voice/tree/stable/",
    branch: "stable",
    doc: "https://discord.js.org/#/docs/voice/stable/",
    data: "",
    search: [],
    classes: [],
    typedefs: [],
  },
  {
    name: "Voice/main",
    url: "https://raw.githubusercontent.com/discordjs/docs/main/voice/main.json",
    github: "https://github.com/discordjs/discord.js/tree/main/",
    branch: "main",
    doc: "https://discord.js.org/#/docs/voice/main/",
    data: "",
    search: [],
    classes: [],
    typedefs: [],
  },
  {
    name: "Rest/main",
    url: "https://raw.githubusercontent.com/discordjs/docs/main/rest/main.json",
    github: "https://github.com/discordjs/discord.js/tree/main/",
    branch: "main",
    doc: "https://discord.js.org/#/docs/rest/main/",
    data: "",
    search: [],
    classes: [],
    typedefs: [],
  },
];

module.exports = { djsdocs };